[book]
authors = ["Sean Bowe"]
language = "en"
src = "src"
title = "The Ragu Book"

[preprocessor.katex]
macros = "macros.txt"
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.0"

[preprocessor.todo]
command = "python3 -c 'import sys,json,os,subprocess as s;a=sys.argv[1:];\nexit(0)if a else None;d=sys.stdin.buffer.read();r=json.loads(d)[0][\"root\"];\np=s.run([sys.executable,os.path.join(r,\"preprocessor-todo.py\")],input=d,stdout=s.PIPE);\nsys.stdout.buffer.write(p.stdout);exit(p.returncode)'"
after = ["links"]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js", "todo.js"]
default-theme = "rust"
preferred-dark-theme = "rust"
additional-css = ["custom.css"]
hash-files = true

# Enable these to generate links with mdbook-rustdoc-link
# Do not check in these uncommented.
# [preprocessor.rustdoc-link]
# after = ["links"]
